### ISSUE TITLE
[Bug] Contract call failing in Remix UI (failing to read on-chain data)

### ISSUE THREAD

**Issue by scorpion9979** [ethereum/remix-project#1282]
I was trying to call my contract that's deployed to Kovan, but I kept getting this Metamask error in my browser console:
``Invalid params: unknown field \`timestamp\`, expected one of \`type\`, \`from\`, \`to\`, \`gasPrice\`, \`gas\`, \`value\`, \`data\`, \`nonce\`, \`accessList\`.``
I tried with my Kovan Infura provider instead on Metamask, still got the same error:
``call to PriceConsumerV3.getLatestPrice errored: Error: Returned error: Invalid params: unknown field `timestamp`, expected one of `type`, `from`, `to`, `gasPrice`, `gas`, `value`, `data`, `nonce`, `accessList`. 
``
I double-checked that the network was switched to Kovan for both times.

The contract call works just fine on Etherscan's contract UI though: https://kovan.etherscan.io/address/0x31C09Eaf8bA8D8FC9Ab044896F870cD737617FF6#readContract

Contract code is available on that same Etherscan link above.

**Comment by chenka** [comment]
Me too, when I called read method from Remix, I alway got this error.

![image](https://user-images.githubusercontent.com/837612/121810886-a9220980-cc8c-11eb-9f65-9460737f2232.png)

but It's work properly when I called from https://kovan.etherscan.io/

**Comment by StephenFluin** [comment]
This seems like a very big deal. I can't read any data from contracts using the Injected Web3 interface. I'm seeing this on newly created & compiled & deployed contracts.

    MetaMask - RPC Error: Invalid params: unknown field `timestamp`, expected one of `type`, `from`, `to`, `gasPrice`, `gas`, `value`, `data`, `nonce`, `accessList`.

**Comment by pappas999** [comment]
I'm also having the same issue

**Comment by JabesSoftware** [comment]
I also have the same issue - can't read data. The contract was working then overnight reading data also returns [object Object].

**Comment by jiaji-wei** [comment]
Same issue to me. I can read data by javascript but all getter were failed via remix.

**Comment by Glenguilin** [comment]
不知道支持中文不

**Comment by LianaHus** [comment]
thanks for reporting this, we will take care of the issue ASAP

**Comment by gperezalba** [comment]
The same problem keeps happening to me.

**Comment by KurtMerbeth** [comment]
![Screenshot from 2021-06-15 15-02-23](https://user-images.githubusercontent.com/22886639/122057335-cff65200-cdea-11eb-9da1-858f67348652.png)

**Comment by Bingyy** [comment]
It is showing this issue is closed but the problem is still happening to the current remix with kovan.

**Comment by AetherFlux** [comment]
The problem is still ongoing on my end as well.

**Comment by pappas999** [comment]
Hi @LianaHus @Aniket-Engg , seems the error is still occurring, despite this issue being closed. Was the updated version deployed to the live site as well? 

For those still stuck, here are a couple of workarounds that can be temporarily used until the live site is fixed:

- You can copy the deployed contract address & ABI from Remix and throw it in [OneClickDapp](https://oneclickdapp.com/) to have the same GUI type interactivity with your deployed contracts
- After deploying via Remix, you can find your contract on  [kovan.etherscan.io](https://kovan.etherscan.io/), and execute functions by going to the Contract tab -> Read Contract button

**Comment by chenka** [comment]
I still have this problem.

![image](https://user-images.githubusercontent.com/837612/122167614-6a1ad080-cea5-11eb-8342-9bf694b837dd.png)

**Comment by Aniket-Engg** [comment]
This is fixed and will be coming as a patch release on live most probably today itself.

In the meantime, you can test it on https://remix-alpha.ethereum.org/

**Comment by Bingyy** [comment]
Awesome, https://remix-alpha.ethereum.org/ is working fine with kovan testnet now.

**Comment by Aniket-Engg** [comment]
FYI, this is live now.

**Comment by leonprou** [comment]
Hey @Aniket-Engg,
It works for Ethereum Mainnet, but the issue persists for Fuse Network (EVM compatible chain).
Details how to connect to Fuse https://docs.fuse.io/the-fuse-chain/network-details

**Comment by leonprou** [comment]
Looking into a fix I see why https://github.com/ethereum/remix-project/pull/1286/files
I assume this should be fixed for all networks that based on parity nodes.

**Comment by gperezalba** [comment]
Problem still needs to be solved for custom chains... @Aniket-Engg Thanks

**Comment by chabashilah** [comment]
I am having the same issue on my private PoA network using Openethereum. @Aniket-Engg Thank you.
