### ISSUE TITLE
remix-tests cli broken on Windows, Remix extension works fine

### ISSUE THREAD

**Issue by Nielsbishere** [ethereum/remix-project#1900]
If I move the file system I have locally to remix.ethereum.org, it works fine, but if I do it locally it does the following:
```
n@I-am-blue MINGW64 /D/.../SystemManager/builds (main)
$ remix-tests -V
0.2.9

n@I-am-blue MINGW64 /D/.../SystemManager/builds (main)
$ remix-tests --optimize true --runs 1000000 -c 0.8.10 ./tests

        👁       :: Running remix-tests - Unit testing for solidity ::   👁

[23:28:11] info: Compiler version set to 0.8.10. Latest version is 0.8.11
[23:28:11] info: Optimization is enabled
[23:28:11] info: Runs set to 1000000
[23:28:11] info: 1 Solidity test file found
Loading remote solc version v0.8.10+commit.fc410830 ...
```
And then it exits without printing any results in both Git BASH (Which is ran above) and Windows command line. 
In the UI I use these settings:
![img](https://user-images.githubusercontent.com/28758736/148615583-ef311e04-0e7e-4a7c-9d23-6581bb19e8f0.png)
And the tests ran (albeit very slowly):
![img](https://user-images.githubusercontent.com/28758736/148615627-79eb72b5-0820-4ea1-951a-11cfb30d1dd8.png)
If I manually run the compiler;
```
n@I-am-blue MINGW64 ~
$ solcjs -V
0.8.10+commit.fc410830.Emscripten.clang

n@I-am-blue MINGW64 /D/.../builds (main)
$ solcjs --bin --abi --verbose --output-dir . --optimize --optimize-runs 1000000 SysManager.sol
```
It produces abi and binaries, but it doesn't generate any output. And it seems like it exits for some reason, I use it in a batch & bash script and it doesn't execute the next line:
```
Compiling SysManager...
```
From script:
```bat
echo Compiling SysManager...
solcjs --bin --abi --verbose --output-dir . --optimize --optimize-runs 1000000 SysManager.sol
echo Compiled SysManager
```
Am I doing something wrong or is there a different problem? I'd love to integrate this into GitHub CI. Maybe it's solcjs exiting the wrong way?

**Comment by Aniket-Engg** [comment]
Thanks for raising this @Nielsbishere . We are trying to reproduce it at our end.

**Comment by Nielsbishere** [comment]
Let me know if you can (or can't) reproduce it, I could send my source code but only via discord or email or something, it's not public yet.

**Comment by Nielsbishere** [comment]
@Aniket-Engg Nope, unfortunately don't have dual boot anymore and no linux/mac VMs either.

**Comment by yann300** [comment]
could you share the contract code you are compiling? I tried locally but it seems to work.
Also can you try to compile without the `--optimize --optimize-runs 1000000` options? Thanks

**Comment by Nielsbishere** [comment]
@yann300  still happens for me, regardless the optimization. I can send you the source via email or discord if you want, it's not public yet. I'll also be looking at if I can run it in a VM to verify if maybe it's a Windows 10 issue.

**Comment by yann300** [comment]
ok thanks, could you send it to remix@ethereum.org ? thanks

**Comment by Nielsbishere** [comment]
@yann300 Sent

**Comment by Nielsbishere** [comment]
Ubuntu seems to handle this just fine, so this might be a problem related to Windows 10

**Comment by yann300** [comment]
sorry for the delay @Nielsbishere 
the contract you sent us doesn't compile, could you resent your last version?
thanks

**Comment by Nielsbishere** [comment]
@yann300 no worries, it doesn't? You gotta do "build test" on windows. I could also send the preprocessed output that is compile ready if that's easier

**Comment by yann300** [comment]
ok could you send the preprocessed outout too? many thanks

**Comment by Nielsbishere** [comment]
Sent 👍

**Comment by Aniket-Engg** [comment]
@Nielsbishere this should be working fine now. Can you please check it with latest version of `remix-tests`?

**Comment by Nielsbishere** [comment]
Hi, sorry for the late response. solc 0.8.10+commit.fc410830.Emscripten.clang and remix-tests 0.2.9 are still hanging for me. 
![Hanging compiler](https://user-images.githubusercontent.com/28758736/152702031-f7187b93-c9c3-47df-ba12-56e40e00e0bd.png)
```batch
echo Compiling SysManager...
solcjs --bin --abi --verbose --output-dir . --optimize --optimize-runs 1000000 SysManager.sol
echo Compiled SysManager
```
And for remix-tests; 
```
echo Starting tests
remix-tests -o true -r 100000 -c 0.8.10 builds/tests/UnitTest_test.sol
echo Finished tests
```
![Hanging tests](https://user-images.githubusercontent.com/28758736/152702058-d8e72ed0-fe10-42dc-bcbe-dcfbc77d1783.png)
This also happens if I disable optimization.

**Comment by Aniket-Engg** [comment]
@Nielsbishere Can you please check with  remix-tests `v0.2.11` if it fixes the issue?

**Comment by Aniket-Engg** [comment]
@Nielsbishere is it fine for you now?

**Comment by Nielsbishere** [comment]
I'm not sure, not working on this anymore.
