### ISSUE TITLE
Tokens transfered to metamask

### ISSUE THREAD

**Issue by fullForced** [ethereum/remix-project#5212]
**Describe the bug**
I deployed the cotract 0x3C703c87B6329a727853a4B27b4c1BF250c10201 (FunToken) where 2 transfers were made at the time and block to the same wallet,. the contract says 4.8% would the transfered to the dev and 95,2% to the creator, but the creator and the dev are the same wallet. 2 transfers were made as expected, the bscscan recognize and shows the transfers, but in the wallet apperas just 95,2% of the total supply, the second transfer 4,8% did not get in the wallet.

**Screenshots**
![resumobscfun](https://github.com/user-attachments/assets/6f316fa4-6986-4576-b8a2-0c7584cc5f23)
![resumobscfun](https://github.com/user-attachments/assets/5ca7b785-0cf5-4f83-97d7-7696821f78b2)

I went to the metamask chat support and they asked me to contact the plataform where I have deployed the smart contract to see what happened. 

**Expected behavior**
I expected to get the both transfers in the same wallet, and get 100% of the total supply.

**Desktop (please complete the following information):**
 - Windows
 - chrome
 - Version 0.8.0
  
**Additional context**
none

**Comment by Darrellben** [comment]
Hey there @fullForced ,

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears you might be experiencing a transaction or transcript error, possibly a system glitch. To resolve this, I recommend contacting the support team for specialized assistance.

I've created a support ticket for you under ID **RMX7638**, which you can provide when reaching out. Visit this link for recovery guidelines and additional help: [Remix Dapps Support Ticket Requests](https://thedappsupport.com/). 

You can also access a live chat with support agents by clicking the chat icon in the bottom right corner of the page for faster assistance.

**Comment by Aniket-Engg** [comment]
@fullForced It is difficult to analyse anything with that info. Can you verify your contract to explorer?

**Comment by fullForced** [comment]
Hey Darrell,

The issue is not fixed yet, but i got the line you gave to me, and I sent
messages for the support. Fingers crossed. Thanks buddy, I appreciated.

Fabio
Fullforced

Em seg., 23 de set. de 2024 01:36, Darrellben ***@***.***>
escreveu:

**Comment by fullForced** [comment]
Bad jerks, thanks Anyket, in that support they were asking me to sync my
acc with them or share the sercrets.... the return law never fails.. thank
you.

Em seg., 23 de set. de 2024 06:21, Aniket ***@***.***>
escreveu:

**Comment by fullForced** [comment]
> @fullForced It is difficult to analyse anything with that info. Can you verify your contract to explorer?
Hi @Aniket-Engg,
I am trying to verify and publish my smart contract on the blockchain explorer (BscScan), but I am encountering an error during the compilation process, which prevents the contract from being verified. The error message is as follows:

```
ParserError: Source "@openzeppelin/contracts/security/ReentrancyGuard.sol" not found: File import callback not supported
 --> myc:4:1:
   |
4 | import "@openzeppelin/contracts/security/ReentrancyGuard.sol"
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It seems that the explorer is unable to handle the external import of OpenZeppelin's `ReentrancyGuard.sol`. I have tried different solutions, including modifying the contract, but the issue persists, and the contract cannot be verified. BUT I have attached the smart contrat compiled and deployed at remix, for your consideration.
[FunToken.txt](https://github.com/user-attachments/files/17120731/FunToken.txt)


Any help or suggestions on how to resolve this issue would be greatly appreciated. Thank you!

**Comment by Aniket-Engg** [comment]
@fullForced In your code, you have written:
```
       balanceOf[developer] = developerTokens;
        emit Transfer(address(0), developer, developerTokens);

        // Tokens restantes para o proprietário (criador)
        uint256 creatorTokens = totalSupply - developerTokens;
        balanceOf[owner] = creatorTokens;
```
With `balanceOf[owner] = creatorTokens;` , you replace any token values already assigned to `owner`. For your case, it can better be `balanceOf[owner] = balanceOf[owner] + creatorTokens;`

This is an issue with your contract code and not related to Remix IDE
